# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1062, 680)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(530, 40, 451, 441))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_go = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_go.setGeometry(QtCore.QRect(30, 360, 151, 61))
        self.btn_go.setObjectName("btn_go")
        self.btn_reset = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_reset.setGeometry(QtCore.QRect(190, 360, 121, 61))
        self.btn_reset.setObjectName("btn_reset")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(50, 40, 41, 32))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 51, 32))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 51, 32))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(50, 210, 51, 32))
        self.label_4.setObjectName("label_4")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_1.setGeometry(QtCore.QRect(300, 30, 113, 41))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 90, 113, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 150, 113, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(300, 210, 113, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_1 = QtWidgets.QLabel(self.groupBox_4)
        self.label_1.setGeometry(QtCore.QRect(110, 40, 131, 41))
        self.label_1.setObjectName("label_1")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(110, 100, 131, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(110, 150, 131, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(110, 200, 131, 41))
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setGeometry(QtCore.QRect(50, 280, 131, 51))
        self.comboBox.setObjectName("comboBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setGeometry(QtCore.QRect(300, 290, 113, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(200, 290, 101, 31))
        self.label_9.setObjectName("label_9")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox.setGeometry(QtCore.QRect(346, 370, 91, 31))
        self.checkBox.setObjectName("checkBox")
        self.btn_close = QtWidgets.QPushButton(Form)
        self.btn_close.setGeometry(QtCore.QRect(870, 550, 151, 91))
        self.btn_close.setObjectName("btn_close")
        self.btn_open = QtWidgets.QPushButton(Form)
        self.btn_open.setGeometry(QtCore.QRect(710, 550, 151, 91))
        self.btn_open.setObjectName("btn_open")
        self.btn_stop = QtWidgets.QPushButton(Form)
        self.btn_stop.setGeometry(QtCore.QRect(530, 550, 151, 91))
        self.btn_stop.setObjectName("btn_stop")
        self.label_8 = QtWidgets.QLabel(Form)      #show image
        self.label_8.setGeometry(QtCore.QRect(20, 40, 471, 431))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_go.setText(_translate("Form", "new"))
        self.btn_reset.setText(_translate("Form", "Go"))
        self.label.setText(_translate("Form", "X"))
        self.label_2.setText(_translate("Form", "Y"))
        self.label_3.setText(_translate("Form", "Z"))
        self.label_4.setText(_translate("Form", "R"))
        self.label_1.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "TextLabel"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "TextLabel"))
        self.label_9.setText(_translate("Form", "time / point"))
        self.checkBox.setText(_translate("Form", "校正"))
        self.btn_close.setText(_translate("Form", "CLOSE"))
        self.btn_open.setText(_translate("Form", "OPEN"))
        self.btn_stop.setText(_translate("Form", "STOP"))
        self.label_8.setText(_translate("Form", "TextLabel"))

